### ISSUE TITLE
Handle duplicated plugin install

### ISSUE THREAD

**Issue by rootwarp** [dsrvlabs/vatz#321]
- parent: #316 
---

Show error message if the user try to install the plugin that is already installed.

Ref. https://github.com/dsrvlabs/vatz/pull/317#issuecomment-1334749495

**Comment by xellos00** [comment]
@rootwarp 
Back in our past discussion, we tried to use `plugin_id` due to its name duplication in different versions and then I thought it's a good idea to create a new primary flag which was `plugin_id`.

I've tried a new identifier which was `plugin_id` to prevent the installation of a duplicate plugin while I was developing PR #428 but decided to remain in current status using the plugin name that user has put as primary key.  It's difficult for VATZ to extract `plugin_id`  to recognize which plugin must be skipped if the user set enable/disable plugin status.

I think it's good to stick around with the current primary key `name` for the plugin table. I am going to close this issue if you don't have any other comment or other option to deal with it.
Please, let me know.

**Comment by xellos00** [comment]
@rootwarp 
I close this issue, because seems you don't have any concern with it.
