### ISSUE TITLE
New Developments: Applying Prometheus as Node exporter

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#342]
- Related: https://github.com/dsrvlabs/vatz/issues/146

---

## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [x] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

Please, Checkout @hqueue Comment on #146
- https://github.com/dsrvlabs/vatz/issues/146#issuecomment-1176418473

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

Implement Prometus for VATZ to collect followings metrics

- VATZ up
- VATZ Running Plugins 

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

### **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@gnongs 
Let me know if you need help, I think we need to finish this anytime soon.

**Comment by xellos00** [comment]
@gnongs 
Do you have any updates with this?

**Comment by gnongs** [comment]
@xellos00 
I'm sorry for the late reply.
The current progress is as follows.
- [x] The current progress is as follows.(We can check Vatz status)
- [ ] Vatz plugin's health check is currently in progress.

Currently, the code is organized to collect per vatz plugin dummy status, but the progress is being delayed because I don't know how to get the status of vatz plugin.

I would appreciate it if you could help me with this.
